In [1]:
import pandas as pd

In [2]:
# Read in generated data from previous notebook
all_data = pd.read_csv('../data/all_data.csv')

In [3]:
def get_percents(timeframes : list, timeframe_column : str):
    """
    Returns the % of contracts and % of dollars awarded to DBE, MBE, WBEs
    """
    df = pd.DataFrame({'timeframe' : timeframes})

#     looks compact but potentially has a divide by zero issue
#     df["percent_dbe_contracts"] = [100 * (all_data[(all_data.DBE__c == True) & (all_data[timeframe_column] == t)].shape[0])/(all_data[(all_data[timeframe_column] == t)].shape[0]) for t in timeframes]
#     df["percent_mbe_contracts"] = [100 * (all_data[(all_data.MBE__c == True) & (all_data[timeframe_column] == t)].shape[0])/(all_data[(all_data[timeframe_column] == t)].shape[0]) for t in timeframes]
#     df["percent_wbe_contracts"] = [100 * (all_data[(all_data.WBE__c == True) & (all_data[timeframe_column] == t)].shape[0])/(all_data[(all_data[timeframe_column] == t)].shape[0]) for t in timeframes]

#     df["percent_dbe_dollars"] = [100 * (all_data[(all_data.DBE__c == True) & (all_data[timeframe_column] == t)].Award_Amount__c.sum())/(all_data[(all_data[timeframe_column] == t)].Award_Amount__c.sum()) for t in timeframes]
#     df["percent_mbe_dollars"] = [100 * (all_data[(all_data.MBE__c == True) & (all_data[timeframe_column] == t)].Award_Amount__c.sum())/(all_data[(all_data[timeframe_column] == t)].Award_Amount__c.sum()) for t in timeframes]
#     df["percent_wbe_dollars"] = [100 * (all_data[(all_data.WBE__c == True) & (all_data[timeframe_column] == t)].Award_Amount__c.sum())/(all_data[(all_data[timeframe_column] == t)].Award_Amount__c.sum()) for t in timeframes]

    
#     less-compact but addresses divide by zero issue
    df_contract_columns = ["percent_dbe_contracts", "percent_mbe_contracts", "percent_wbe_contracts"]
    df_dollars_columns = ["percent_dbe_dollars", "percent_mbe_dollars", "percent_wbe_dollars"]
    all_data_columns = ["DBE__c", "MBE__c", "WBE__c"]
    
    for i,x in enumerate(all_data_columns):
        value = []
        for t in timeframes:
            a = all_data[(all_data[x] == True) & (all_data[timeframe_column] == t)].shape[0]
            b = all_data[(all_data[timeframe_column] == t)].shape[0]
            percent = 100*a/b if b != 0 else 0
            value.append(percent)
        df[df_contract_columns[i]] = value
        
    for i,x in enumerate(all_data_columns):
        value = []
        for t in timeframes:
            a = all_data[(all_data[x] == True) & (all_data[timeframe_column] == t)].Award_Amount__c.sum()
            b = all_data[(all_data[timeframe_column] == t)].Award_Amount__c.sum()
            percent = 100*a/b if b != 0 else 0
            value.append(percent)
        df[df_dollars_columns[i]] = value
          
    return df

In [4]:
# Generate google sheet for yearly analysis
years = sorted(all_data.bid_due_year.unique())
get_percents(years, 'bid_due_year')

# TODO: write to google sheet

,timeframe,percent_dbe_contracts,percent_mbe_contracts,percent_wbe_contracts,percent_dbe_dollars,percent_mbe_dollars,percent_wbe_dollars
0,2016,25.908430,24.127907,17.114826,1.095615,1.257868,0.346887
1,2017,2.933608,3.499743,2.367473,0.857637,1.788530,0.561600
2,2018,26.986379,22.531215,16.259932,3.922398,3.976587,2.540704
3,2019,4.658982,4.947166,3.170029,1.823672,2.291452,1.437403
4,2020,3.120760,2.645862,1.628223,0.552334,0.595294,0.184383
5,2021,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [5]:
# Generate google sheet for monthly analysis
months = sorted(all_data.bid_due_year_month.unique())
get_percents(months, 'bid_due_year_month')

# TODO: write to google sheet

,timeframe,percent_dbe_contracts,percent_mbe_contracts,percent_wbe_contracts,percent_dbe_dollars,percent_mbe_dollars,percent_wbe_dollars
0,2016-07,1.941748,3.883495,0.970874,1.630674,2.096960,0.414954
1,2016-08,0.000000,1.075269,0.000000,0.000000,0.108007,0.000000
2,2016-09,1.875000,3.125000,3.125000,0.594589,0.559250,0.598821
3,2016-10,21.561969,18.336163,15.619694,1.380320,1.380320,0.026856
4,2016-11,38.092061,35.423616,24.082722,1.598780,1.603889,0.000000
...,...,...,...,...,...,...,...
57,2021-04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
58,2021-05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
59,2021-06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60,2021-07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
61,2021-08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [ ]:
# main